name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main
jobs:
  run-linters:
    name: Run linters
    steps:
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          # prettier: true